In [1]:
import pandas as pd

In [2]:
shelf = pd.read_pickle('data/food_shelves_enriched.pkl')
shelf.isna().sum()

name       0
address    0
lat        0
lng        0
county     0
dtype: int64

In [3]:
len(shelf)

549

In [11]:
shelf.loc[~shelf['address'].str.contains('MN')].loc[~shelf['address'].str.contains('Mn')]

,name,address,lat,lng,county
66,Century College Food Pantry,Century College,45.041577,-92.982349,Washington County
81,Cokato Food Shelf,"395 Broadway Ave S, Cokato, Minnesota, USA",45.075426,-94.189889,Wright County
101,Deer River Area Food Shelf,Goodall Resource Center,47.344443,-93.794391,Itasca County
106,Dorothy Day Food Pantry West Fargo,"45 21st Ave W, West Fargo, ND 58078, USA",46.847215,-96.904977,Cass County
117,Emergency Food Pantry,"1101 4th Ave N, Fargo, ND 58102, USA",46.880891,-96.796064,Cass County
123,Family Pathways Frederic,"1100 Wisconsin Ave, Frederic, WI 54837, USA",45.667212,-92.465535,Polk County
129,Family Pathways St. Croix Falls,"2000 U.S. 8, St Croix Falls, WI 54024, USA",45.396728,-92.571364,Polk County
180,Glyndon Community Food Pantry,"414 Parke Avenue South, Glyndon, Minnesota 565...",46.872291,-96.579746,Clay County
216,Hope for the Community Huntington Place Apartm...,"5805 73rd Ave N, Brooklyn Park, Minnesota 5542...",45.086832,-93.353550,Hennepin County
324,New Life Center,"1902 3rd Ave N, Fargo, ND 58102, USA",46.879236,-96.811725,Cass County
363,Pierce County Food Pantry,"440 N Maple St, Ellsworth, WI 54011, USA",44.738232,-92.486113,Pierce County
390,Richland Wilkin Food Pantry,"699 8th Ave S, Wahpeton, ND 58075",46.256838,-96.609559,Richland County
405,Salvation Army Fargo,"304 Roberts Street, Fargo, ND 58102",46.879071,-96.789184,Cass County
407,Salvation Army Grand Forks Food Shelf,"1600 University Ave, Grand Forks, ND 58203",47.922268,-97.049379,Grand Forks County
433,Second Harvest Northland: Douglas County,"11523 S Business 53, Solon Springs, Wisconsin,...",46.348346,-91.820710,Douglas County
434,Second Harvest Northland: Iron County,"606-607 3rd Avenue North, Hurley, WI, USA",46.455190,-90.183996,Iron County
459,Spring Valley Community Food Pantry,"S425 Church Avenue, Spring Valley, Pierce, WI ...",44.842849,-92.231715,Pierce County
464,St. Joseph’s Social Care Food Pantry,"620 8th Ave South, Grand Forks, ND 58201",47.914466,-97.034715,Grand Forks County
466,St. Mary’s Food Pantry,"1331 10th Street N, Fargo, ND 58102",46.893515,-96.793687,Cass County
542,Wheaton Community Food Shelf,First Presbyterian Church,45.804405,-96.499233,Traverse County

In [5]:
shelf.loc[shelf['name'].str.contains('Salvation Army')]

,name,address,lat,lng,county
400,Salvation Army – St Paul Eastside,"1019 Payne Ave, St. Paul, MN 55101",44.971806,-93.073969,Ramsey County
401,Salvation Army Anoka County,"1201 89th Ave NE Suite 130, Blaine, MN, 55113",45.132953,-93.239593,Anoka County
402,Salvation Army Austin,"409 1st Ave NE, Austin, MN 55912",43.667457,-92.970887,Mower County
403,Salvation Army Central Minneapolis Food Shelf,"2727 Central Ave NE, Minneapolis, MN 55418",45.049110,-93.247461,Anoka County
404,Salvation Army Duluth,"215 S 27th Ave W, Duluth, MN 55806",46.759980,-92.129664,St. Louis County
405,Salvation Army Fargo,"304 Roberts Street, Fargo, ND 58102",46.879071,-96.789184,Cass County
406,Salvation Army Fergus Falls,"622 E Vernon Ave, Fergus Falls, MN 56537",46.278336,-96.064796,Otter Tail County
407,Salvation Army Grand Forks Food Shelf,"1600 University Ave, Grand Forks, ND 58203",47.922268,-97.049379,Grand Forks County
408,Salvation Army Hibbing,"107 W Howard Street, Hibbing, MN 55746",47.427318,-92.942216,St. Louis County
409,Salvation Army International Falls,"1301 3rd Ave W, International Falls, MN 56649",48.592848,-93.394554,Koochiching County
410,Salvation Army Lakewood Food Shelf,"2080 Woodlyn Ave, Maplewood, MN 55109",45.032671,-93.013134,Ramsey County
411,Salvation Army Mankato,"700 S Riverfront Drive, Mankato, MN 56001",44.162421,-94.009446,Blue Earth County
412,Salvation Army North Minneapolis Food Shelf,"2024 Lyndale Ave N, Minneapolis, MN 55411",44.999891,-93.287549,Hennepin County
413,Salvation Army Prince of Peace Food Shelf,"13801 Fairview Drive, Burnsville, MN, USA",44.752169,-93.274614,Dakota County
414,Salvation Army Rochester,"115 1st Avenue Northeast, Rochester, MN, USA",44.025110,-92.461916,Olmsted County
415,Salvation Army South Office,"1604 E Lake Street, Minneapolis, MN 55407",44.948367,-93.251141,Hennepin County
416,Salvation Army St. Cloud,"400 Highway 10 S, St. Cloud, MN 56304",45.564306,-94.153292,Benton County
417,Salvation Army Virginia,"507 12th Ave W, Virginia, MN 55792",47.519348,-92.552013,St. Louis County
490,The Salvation Army – Cloquet Food Shelf,"316 Carlton Ave, Cloquet, MN 55720",46.717725,-92.460218,Carlton County
491,The Salvation Army – Montgomery Food Shelf,"151 Elm Avenue Southeast, Montgomery, MN 56069...",44.436940,-93.580282,Le Sueur County
492,The Salvation Army – Temple Corps,"1604 E Lake Street, Minneapolis, MN 55407",44.948656,-93.250781,Hennepin County
493,The Salvation Army Albert Lea,"302 Court Street, Albert Lea, MN 56007",43.646888,-93.369992,Freeborn County
494,The Salvation Army Brainerd,"208 S 5th Street, Brainerd, MN 56401",46.356710,-94.202166,Crow Wing County
495,The Salvation Army Fairmont,"303 Downtown Plaza, Fairmont, MN, USA",43.655042,-94.462848,Martin County
496,The Salvation Army St. Paul Citadel,"401 W 7th Street, St. Paul, MN 55102",44.939477,-93.109402,Ramsey County

In [ ]:
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(shelf)

In [ ]:
shelf = pd.read_pickle('data/clean_food_shelf_list.pkl')

with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(shelf.loc[shelf['match'] != 'Match', 'address'])